name: Test
on:
  push:

concurrency:
  group: check-build-lin-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build - ${{ matrix.config.os }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: ubuntu-24.04
            name: "Ubuntu 24.04"
    steps:
      - name: Set up GCC 11
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt-get install -y gcc-11 g++-11
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 60
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-11 60
          sudo update-alternatives --set gcc /usr/bin/gcc-11
          sudo update-alternatives --set g++ /usr/bin/g++-11

      - name: Install Cuda
        uses: Jimver/cuda-toolkit@v0.2.15
        with:
          cuda: '11.7.0'

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Artifacts
          overwrite: true
          path: "/var/log/cuda-installer.log"

      - name: Test
        shell: bash
        run: |
          gcc --version
