name: Test
on:
  push:

concurrency:
  group: check-build-lin-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build - ${{ matrix.config.os }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: ubuntu-24.04
            name: "Ubuntu 24.04"
    steps:
      - name: Install Cuda
        uses: Jimver/cuda-toolkit@v0.2.10
        with:
          cuda: '11.7.0'

      - name: Test
        shell: bash
        run: |
          gcc --version
